var PlonksTestData = {
    "type": "FeatureCollection",
    "name": "PlonksTest",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
    "features": [
    { "type": "Feature", "properties": { "Name": "42 Suir Street", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "Info": "Blue and white street signs (Bluff specific). <br> White sign post. <br> Red triangle 'Give Way' sign. <br> <a href='https://www.youtube.com/watch?v=UtAFVBt6HNk'> A good song to remember that the Bluff is the southernmost port city in NZ. </a>" }, "geometry": { "type": "Point", "coordinates": [ 168.3266644, -46.5971253, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "22 Eversham Road", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "Info": "Blue and white street signs. <br> Driving on left." }, "geometry": { "type": "Point", "coordinates": [ 176.2242626, -37.6768903, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "39°17'25.5\"S 175°44'26.2\"E", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "Info": "White bollards with red wraparound stripes." }, "geometry": { "type": "Point", "coordinates": [ 175.740611111111008, -39.290416666666701, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "1 Glasgow Street", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "Info": "Give-way triangle and give-way sign. <br> Wellington is known for its hillscape." }, "geometry": { "type": "Point", "coordinates": [ 174.7667529, -41.2871999, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "37 Coutts Street", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "Info": "Black and white license plates. <br> .nz TLD. <br> Wellington is known for its hillscape." }, "geometry": { "type": "Point", "coordinates": [ 174.796064, -41.3199787, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "38°00'00.6\"S 175°49'15.4\"E", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "Info": "Green chevron highway signs. <br> Highway 5 (with red crest). <br> Shire-like hills." }, "geometry": { "type": "Point", "coordinates": [ 175.820944444443995, -38.000166666666701, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "309 Limeworks Loop Road", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": -1, "extrude": 0, "visibility": -1, "drawOrder": null, "icon": null, "Info": "Ferns on side of road. <br> White bollards with red wraparound stripes." }, "geometry": { "type": "Point", "coordinates": [ 175.1064783, -37.9256955, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "Morelea Farm", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": null, "extrude": null, "visibility": null, "drawOrder": null, "icon": null, "Info": "Sheep on side of road." }, "geometry": { "type": "Point", "coordinates": [ 170.859823618131657, -44.088866553064285, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "324 New Renwick Road", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": null, "extrude": null, "visibility": null, "drawOrder": null, "icon": null, "Info": "Metal fence post. <br> Mountains in background." }, "geometry": { "type": "Point", "coordinates": [ 173.906696554902084, -41.53055821115759, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "Peacemaker", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": null, "extrude": null, "visibility": null, "drawOrder": null, "icon": null, "Info": "Glacial lake. <br> Mountains in background." }, "geometry": { "type": "Point", "coordinates": [ 169.249393523718226, -44.595223914776732, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "Waiomo Road", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": null, "extrude": null, "visibility": null, "drawOrder": null, "icon": null, "Info": "Wooden fence posts. <br> White bollards with red wraparound stripes. <br> Slightly more lush. <br> Hilly landscape." }, "geometry": { "type": "Point", "coordinates": [ 174.073057280024273, -35.410549462041679, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "Alexandra-Fruitlands Road", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": null, "extrude": null, "visibility": null, "drawOrder": null, "icon": null, "Info": "Vegetation is more sparse." }, "geometry": { "type": "Point", "coordinates": [ 169.333470489331233, -45.301292520489184, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "Press Lane", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": null, "extrude": null, "visibility": null, "drawOrder": null, "icon": null, "Info": "03 Area code." }, "geometry": { "type": "Point", "coordinates": [ 172.638029968357358, -43.530591918341877, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "Haast Highway 6", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": null, "extrude": null, "visibility": null, "drawOrder": null, "icon": null, "Info": "Highway 6. <br> Green chevron highway sign (with red crest). <br> Mountains in background. <br> White sign post. <br> Blue and white street sign." }, "geometry": { "type": "Point", "coordinates": [ 169.045573678428354, -43.859982622863782, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "Highway 85", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": null, "extrude": null, "visibility": null, "drawOrder": null, "icon": null, "Info": "Snow coverage. <br> White bollards with red wraparound stripes." }, "geometry": { "type": "Point", "coordinates": [ 169.783852409655964, -44.980917395027213, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "63 Victoria St W", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": null, "extrude": null, "visibility": null, "drawOrder": null, "icon": null, "Info": "09 Area code. <br> Auckland sky tower. <br>" }, "geometry": { "type": "Point", "coordinates": [ 174.763067076977251, -36.848354551536318, 0.0 ] } },
    { "type": "Feature", "properties": { "Name": "Bowman Road and Highway 2", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": null, "extrude": null, "visibility": null, "drawOrder": null, "icon": null, "Info": "Dark blue Google car. <br> Blue and white street signs. <br> White sign posts. <br> Tightly packed wooden fences. <br> 'Give Way' Triangles. <br> Hilly, warmer landscape." }, "geometry": { "type": "Point", "coordinates": [ 175.87389936945749, -40.365442110203062, 0.0 ] } }
    ]
    }
    
